linkcouchUIImage: eahedav/linkcouch-ui:latest
linkcouchAPIImage: eahedav/linkcouch-backend:latest
linkcouchScreenshotsAPIImage: eahedav/linkcouch-screenshots-api:latest
rabbitMqImage: bitnami/rabbitmq:latest

rabbitmq:
  rabbitmqUsername: user
  rabbitmqPassword: password
  rabbitmqNodePort: 5672
  rabbitmqNodeType: stats
  rabbitmqNodeName: rabbit
  rabbitmqVhost: /
  rabbitmqManagerPort: 15672

serviceType: ClusterIP

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m