linkcouchUIImage: eahedav/linkcouch-ui:latest
linkcouchAPIImage: eahedav/linkcouch-backend:latest
linkcouchScreenshotsAPIImage: eahedav/linkcouch-screenshots-api:latest
rabbitMqImage: bitnami/rabbitmq:latest

rabbitmq:
  rabbitmqUsername: user
  rabbitmqPassword: password
  rabbitmqNodePort: 5672
  rabbitmqNodeType: stats
  rabbitmqNodeName: rabbit
  rabbitmqVhost: /
  rabbitmqManagerPort: 15672

serviceType: ClusterIP

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m

hub:
  image: "selenium/hub"
  tag: "3.4.0"
  pullPolicy: "IfNotPresent"
  port: 4444
  readinessTimeout: 1
  javaOpts: "-Xmx400m"
  resources:
    limits:
      cpu: ".5"
      memory: "512Mi"
  serviceType: "LoadBalancer"
  serviceSessionAffinity: "None"

chrome:
  enabled: false
  image: "selenium/node-chrome"
  tag: "3.4.0"
  pullPolicy: "IfNotPresent"
  replicas: 1
  javaOpts: "-Xmx900m"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  resources:
    limits:
      cpu: ".5"
      memory: "1000Mi"