apiVersion: v1
kind: Service
metadata:
  name: linkcouch-api
  labels:
    app: linkcouch-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: epmd
    port: 3000
    targetPort: 3000
  selector:
    app: linkcouch-api