apiVersion: v1
kind: Service
metadata:
  name: {{ template "linkcouch-screenshots-api.fullname" . }}
  labels:
    app: {{ template "linkcouch-screenshots-api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: {{ template "linkcouch-screenshots-api.fullname" . }}
    port: 3000
    targetPort: 3001
  selector:
    app: {{ template "linkcouch-screenshots-api.fullname" . }}