apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkcouch-ui
  labels:
    app: linkcouch-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: linkcouch-ui
    spec:
      containers:
      - name: linkcouch-ui
        image: "{{ .Values.linkcouchUIImage }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ports:
          - name: linkcouch-ui
            containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 100m