apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ template "linkcouch-ui.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "linkcouch-ui.fullname" . }}
          servicePort: 80
      - path: /linkcouch-api/*
        backend:
          serviceName: {{ template "linkcouch-api.fullname" . }}
          servicePort: 3000