apiVersion: v1
kind: Service
metadata:
  name: linkcouch-ui
  labels:
    app: linkcouch-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: linkcouch-ui
    port: 80
    targetPort: 80
  selector:
    app: linkcouch-ui